name: Deployment1
on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm build
      - name: Deploy
        run: echo "Deploying...."
